# Generated by Django 4.0.1 on 2022-07-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_ambassadorimage_ambassador_workshopimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovatorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regIsOpen', models.BooleanField()),
                ('regLink', models.TimeField(default=None)),
            ],
        ),
    ]
