# Generated by Django 4.0.1 on 2022-07-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_innovatorregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovatorregistration',
            name='regLink',
            field=models.TextField(default=None),
        ),
    ]
