# Generated by Django 4.0.1 on 2022-07-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_innovatorregistration_reglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupimage',
            name='Event',
        ),
        migrations.RemoveField(
            model_name='workshopimage',
            name='Event',
        ),
        migrations.DeleteModel(
            name='StartUp',
        ),
        migrations.DeleteModel(
            name='StartUpImage',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
        migrations.DeleteModel(
            name='WorkshopImage',
        ),
    ]
